hostname spine2
!
log stdout
!
interface eth1
 ip address 10.0.2.1/30
 ip ospf network point-to-point
 ip ospf area 0.0.0.0
!
interface eth2
 ip address 10.0.4.1/30
 ip ospf network point-to-point
 ip ospf area 0.0.0.0
!
interface eth3
 ip address 10.0.6.1/30
 ip ospf network point-to-point
 ip ospf area 0.0.0.0
!
interface lo
 ip address 1.1.1.2/32
 ip ospf area 0.0.0.0
!
router bgp 65000
 bgp router-id 1.1.1.2
 no bgp ebgp-requires-policy
 !
 neighbor 10.0.2.2 remote-as 65001
 neighbor 10.0.4.2 remote-as 65002
 neighbor 10.0.6.2 remote-as 65003
 !
 address-family ipv4 unicast
  neighbor 10.0.2.2 activate
  neighbor 10.0.4.2 activate
  neighbor 10.0.6.2 activate
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor 10.0.2.2 activate
  neighbor 10.0.4.2 activate
  neighbor 10.0.6.2 activate
  neighbor 10.0.2.2 route-reflector-client
  neighbor 10.0.4.2 route-reflector-client
  neighbor 10.0.6.2 route-reflector-client
 exit-address-family
!
router ospf
 ospf router-id 1.1.1.2
 log-adjacency-changes
!
line vty
!
end
